apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parcial1-patrones-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/julianpiav/Parcial1-Patrones-Back-end'
    targetRevision: HEAD
    path: '.'  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
