apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: argocd
  
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage 
  hostPath:
    path: /mnt/data/mysql


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: argocd
spec:
  storageClassName: do-block-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv



