apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argocd
  
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002